name: 안드로이드 디버그 및 릴리즈 빌드

on:
  workflow_dispatch: # Actions 탭에서 수동으로 실행 가능

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. 소스 코드 가져오기
      - name: Checkout
        uses: actions/checkout@v4

      # 2. JDK 17 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # 3. gradlew 실행 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # ====================================================================
      # 4. 릴리즈 빌드를 위한 서명 키 파일 준비 (Secrets 사용)
      #    Base64로 인코딩된 Secret을 다시 .jks 파일로 디코딩하여 생성
      # ====================================================================
      - name: Decode Keystore
        env:
          SIGNING_KEY_JKS_FILE_B64: ${{ secrets.SIGNING_KEY_JKS_FILE }}
        run: |
          echo $SIGNING_KEY_JKS_FILE_B64 | base64 --decode > app/my-release-key.jks

      # 5. 디버그 APK 빌드
      - name: Build debug APK
        run: ./gradlew assembleDebug

      # 6. 릴리즈 APK 빌드 (Secrets에 저장된 값들을 환경변수로 전달)
      - name: Build release APK
        env:
          SIGNING_KEY_STORE_PASSWORD: ${{ secrets.SIGNING_KEY_STORE_PASSWORD }}
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PRIVATE_PASSWORD: ${{ secrets.SIGNING_KEY_PRIVATE_PASSWORD }}
        run: |
          ./gradlew assembleRelease \
            -Pandroid.injected.signing.store.file=$(pwd)/app/my-release-key.jks \
            -Pandroid.injected.signing.store.password=$SIGNING_KEY_STORE_PASSWORD \
            -Pandroid.injected.signing.key.alias=$SIGNING_KEY_ALIAS \
            -Pandroid.injected.signing.key.password=$SIGNING_KEY_PRIVATE_PASSWORD

      # 7. 빌드된 디버그 APK 업로드
      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk

      # 8. 빌드된 릴리즈 APK 업로드
      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/release/app-release-unsigned.apk # Gradle 버전에 따라 이름이 다를 수 있음
